### AUTOMATICALLY GENERATED BY generateInputFile() ###
###                EDIT AT OWN RISK                ###
## Propellant section
Propellant

#Propellant with ID 657: NITROUS OXIDE                  
+657 6000.000000  g

#Propellant with ID 1032: paraffin 0907                  
+1032 1000.000000  g

## Frozen performance with area ratio exit condition
FR
+chamber_pressure 50.000000 bar 
+supersonic_area_ratio 5.000000 
