%% Gasdynamics
% This function computes the thrust coefficient for the isentropic flow

function thrustCoefficient = ...
    getThrustCoefficient( ...
        SpecificHeatRatio, AreaRatio, AmbientPressureRatio)
    
    [~, SupersonicMachNumber] = ...
        getIsentropicMachFromAreaRatio(SpecificHeatRatio, AreaRatio);
    
    % pe/p0
    ExitPressureRatio = ...
        getIsentropicPressureRatio(SpecificHeatRatio, SupersonicMachNumber);
    
    % Based on Shapiro vol. 1 p. 101 eq. 4.33
    f = @(k,M) ...
        k ...
        * sqrt((2/(k-1))*(2/(k+1))^((k+1)/(k-1))) ...
        * sqrt((1-ExitPressureRatio^((k-1)/(k)))) ...
        + AreaRatio * (ExitPressureRatio - AmbientPressureRatio);
    
    thrustCoefficient = f(SpecificHeatRatio, SupersonicMachNumber);
end
